name: macos-build
on:
  pull_request:
  release:
    types: [published]
  push:
    # tags: [v*.*.*] # Uncomment and specify valid tags if needed, or remove this line
    branches:
      - macos-github-actions-tests

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false

      matrix:
        build_type:
            - Release
            - Debug
        developer_mode:
            - ON
            - OFF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python (per Conan)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Conan
        run: |
          pip install conan
          conan --version

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies using Conan
        run: |
          conan install . -of build \
            --build=missing \
            --settings=build_type=${{ matrix.build_type }}

      - name: Install developer tools
        run: |
          brew install llvm cppcheck
      - name: Add llvm to PATH
        run: |
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" \
            -DENABLE_DEVELOPER_MODE:BOOL=${{matrix.developer_mode}} \
            -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} \
            -DENABLE_COVERAGE:BOOL=OFF \
            -DDISABLE_STACK_PROTECTION:BOOL=ON \
            -DDISABLE_ELF_PROTECTION:BOOL=ON
  
      - name: Build
        run: |
          cmake --build ./build --config ${{ matrix.build_type }} -- -j$(sysctl -n hw.ncpu)

      - name: Run tests
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build_type }} --output-on-failure