name: macos-build
on:
  pull_request:
  release:
    types: [published]
  push:
    # tags: [v*.*.*] # Uncomment and specify valid tags if needed, or remove this line
    branches:
      - macos-github-actions-tests

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python (per Conan)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Conan
        run: |
          pip install conan
          conan --version

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies using Conan
        run: |
          conan install . -of build \
            --build=missing \
            --settings=build_type=Release

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build ./build --config Release -- -j$(sysctl -n hw.ncpu)

      - name: Run tests
        working-directory: ./build
        run: |
          ctest -C Release --output-on-failure
