name: macos-build
on:
  pull_request:
  release:
    types: [published]
  push:
    # tags: [v*.*.*] # Uncomment and specify valid tags if needed, or remove this line
    branches:
      - macos-github-actions-tests

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew dependencies
        run: |
          # Aggiorna Homebrew
          brew update
          
          # Installazione librerie principali
          brew install cmake openssl fmt catch2 cli11 spdlog nlohmann-json asio

          # Verifica le versioni installate
          cmake --version
          brew list --versions

      - name: Configure CMake
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(brew --prefix)

      - name: Build
        run: |
          cmake --build ./build --config Release

      - name: Run tests
        working-directory: ./build
        run: |
          ctest -C Release --output-on-failure
