name: macOS CI
on:
  pull_request:
  release:
    types: [published]
  push:
    # tags: [v*.*.*] # Uncomment and specify valid tags if needed, or remove this line
    branches:
      - main
      - develop
      - macos-github-actions-tests

env:
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

jobs:
  Test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
            - macos-14
            - macos-15
            - macos-26
        build_type:
            - Release
            - Debug
        developer_mode:
            - ON
            - OFF
        standard:
            - 17
            - 20
            - 23
            - 26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: clang
          build_type: ${{ matrix.build_type }}
          developer_mode: ${{ matrix.developer_mode }}

      - name: Install Python (for Conan)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Conan
        run: |
          pip install conan
          conan --version

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Install dependencies using Conan
        run: |
          conan install . -of build \
            --build=missing \
            --settings=build_type=${{ matrix.build_type }}

      - name: Install developer tools
        run: |
          brew install llvm cppcheck

      - name: Add llvm to PATH
        run: |
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Configure CMake (with Retry for External Downloads)
        uses: nick-invision/retry@v3
        with:
          max_attempts: 3
          retry_wait_seconds: 10
          timeout_minutes: 2
          command: |
            cmake \
              -S . \
              -B ./build \
              -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" \
              -DENABLE_DEVELOPER_MODE:BOOL=${{matrix.developer_mode}} \
              -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} \
              -DENABLE_COVERAGE:BOOL=OFF \
              -DDISABLE_STACK_PROTECTION:BOOL=ON \
              -DDISABLE_ELF_PROTECTION:BOOL=ON \
              -DCMAKE_CXX_STANDARD=${{ matrix.standard }} \
              -DGIT_SHA:STRING=${{ github.sha }}
  
      - name: Build
        run: |
          cmake --build ./build --config ${{ matrix.build_type }} -- -j$(sysctl -n hw.ncpu)

      - name: Run tests
        working-directory: ./build
        run: |
          ctest -C ${{ matrix.build_type }} --output-on-failure